# src/lang_utils.py

def get_text(lang):
    return {
        "tab_titles": {
            "RAG": "RAG 数据库管理" if lang == "中文" else "RAG Database",
            "Literature": "文献综述 + 问答数据库" if lang == "中文" else "Literature Review PLUS Database Q&A",
            "Anki": "Anki 记忆卡片" if lang == "中文" else "Anki Cards",
            "LitMap": "LitMap 知识图谱" if lang == "中文" else "LitMap Knowledge Graph",
        },
        "rag_tab": {
            "header": "RAG：项目与文件管理" if lang == "中文" else "RAG: Project and File Management",
            "select_project": "选择项目：" if lang == "中文" else "Select Project:",
            "new_project": "新建项目" if lang == "中文" else "New Project",
            "project_name_placeholder": "请输入新项目名称：" if lang == "中文" else "Enter new project name:",
            "create_btn": "创建项目" if lang == "中文" else "Create Project",
            "success": "✅ 项目 {name} 创建成功！" if lang == "中文" else "✅ Project {name} created successfully!",

            "step1_title": "### 步骤1：上传文件" if lang == "中文" else "### Step 1: Upload Files",
            "uploader_label": "上传 PDF/MD/DOCX/XLSX/HTML" if lang == "中文" else "Upload PDF/MD/DOCX/XLSX/HTML",
            "already_exists": "'{name}' 已存在。" if lang == "中文" else "'{name}' already exists.",
            "upload_success": "已上传: {files}" if lang == "中文" else "Uploaded: {files}",
            "no_new_file": "无新文件。" if lang == "中文" else "No new files.",
            "please_upload": "请上传文件。" if lang == "中文" else "Please upload files.",

            "db_overview": "数据库概览" if lang == "中文" else "Database Overview",
            "refresh_stats": "刷新统计信息" if lang == "中文" else "Refresh Statistics",
            "embedding_model": "嵌入模型" if lang == "中文" else "Embedding Model",
            "total_chunks": "总分块数" if lang == "中文" else "Total Chunks",
            "embedded_chunks": "已嵌入分块" if lang == "中文" else "Embedded Chunks",
            "document_count": "文档数量" if lang == "中文" else "Document Count",
            "chunks_embedded": "分块已嵌入" if lang == "中文" else "chunks embedded",
            "details": "详细信息" if lang == "中文" else "Details",
            "last_updated": "最后更新" if lang == "中文" else "Last Updated",
            "avg_content_length": "平均内容长度" if lang == "中文" else "Average Content Length",
            "dedup_status": "去重状态" if lang == "中文" else "Deduplication Status",
            "dedup_enabled": "已启用" if lang == "中文" else "Enabled",
            "dedup_disabled": "未启用" if lang == "中文" else "Disabled",
            "db_operations": "数据库操作" if lang == "中文" else "Database Operations",
            "db_health_check": "健康检查" if lang == "中文" else "Health Check",
            "check_db": "检查数据库连接和完整性" if lang == "中文" else "Check database connection and integrity",
            "db_healthy": "数据库健康，包含" if lang == "中文" else "Database is healthy, contains",
            "db_healthy_embeddings": "个嵌入向量" if lang == "中文" else "embeddings",
            "db_connection_failed": "数据库连接失败:" if lang == "中文" else "Database connection failed:",
            "remove_duplicates": "清理重复项" if lang == "中文" else "Remove Duplicates",
            "remove_duplicates_help": "删除重复的嵌入向量以优化存储" if lang == "中文" else "Remove duplicate embeddings to optimize storage",
            "duplicates_removed": "已删除" if lang == "中文" else "Removed",
            "duplicates_count": "个重复项" if lang == "中文" else "duplicates",
            "no_duplicates": "未发现重复项" if lang == "中文" else "No duplicates found",
            "remove_duplicates_failed": "清理重复项失败:" if lang == "中文" else "Failed to remove duplicates:",
            "danger_zone": "危险区域" if lang == "中文" else "Danger Zone",
            "irreversible_warning": "以下操作不可逆，请谨慎操作" if lang == "中文" else "The following operations are irreversible, please proceed with caution",
            "confirm_clear_all": "我确认要清空所有嵌入向量" if lang == "中文" else "I confirm to clear all embeddings",
            "clear_all_embeddings": "清空所有嵌入" if lang == "中文" else "Clear All Embeddings",
            "clear_all_help": "删除所有嵌入向量，保留文档和分块" if lang == "中文" else "Delete all embeddings while keeping documents and chunks",
            "clear_success": "所有嵌入已清空" if lang == "中文" else "All embeddings cleared",
            "clear_failed": "清空失败" if lang == "中文" else "Clear operation failed",
            "clear_failed_error": "清空操作失败:" if lang == "中文" else "Clear operation failed:",
            "stats_error": "获取统计信息失败:" if lang == "中文" else "Failed to get statistics:",

            "step2_title": "### 步骤2：预处理文件（分块）" if lang == "中文" else "### Step 2: Preprocess Files (Chunking)",
            "chunk_method": "分块方式：" if lang == "中文" else "Chunking method:",
            "chunk_methods": ["按句子","按段落","按页","固定长度"] if lang == "中文" else ["By Sentence","By Paragraph","By Page","Fixed Length"],
            "chunk_length": "固定长度" if lang == "中文" else "Fixed Length",
            "chunk_length_label": "分块长度（字符）" if lang == "中文" else "Chunk length (chars)",
            "force_reprocess": "强制全部重新预处理（忽略 hash，适用于参数变更或修复）" if lang == "中文" else "Force full reprocessing (ignore hash; for param change/fix)",
            "start_preprocess": "开始预处理" if lang == "中文" else "Start Preprocessing",
            "preprocess_success": "预处理完成！" if lang == "中文" else "Preprocessing complete!",
            "preprocess_fail": "预处理失败: {err}" if lang == "中文" else "Preprocessing failed: {err}",

            "step3_title": "### 步骤3：生成/更新向量" if lang == "中文" else "### Step 3: Create/Update Embeddings",
            "embed_mode": "向量生成方式：" if lang == "中文" else "Embedding mode:",
            "embed_modes": ["全部重新生成向量","仅新增分块"] if lang == "中文" else ["Embed all","Only new chunks"],
            "only_new_chunks": "仅新增分块" if lang == "中文" else "Only new chunks",
            "mode_help_only_new": "仅处理新上传或未嵌入的分块，节省时间和成本" if lang == "中文" else "Only process newly uploaded or unembedded chunks to save time and cost",
            "mode_help_embed_all": "重新处理所有分块，确保数据一致性" if lang == "中文" else "Reprocess all chunks to ensure data consistency",
            "advanced_options": "高级选项" if lang == "中文" else "Advanced Options",
            "force_reprocess_embed": "强制重新处理所有向量" if lang == "中文" else "Force reprocess all embeddings",
            "force_reprocess_embed_help": "忽略现有向量，重新生成所有向量" if lang == "中文" else "Ignore existing embeddings and regenerate all",
            "enable_deduplication": "启用去重" if lang == "中文" else "Enable Deduplication",
            "enable_deduplication_help": "防止重复内容生成多个向量" if lang == "中文" else "Prevent duplicate content from generating multiple embeddings",
            "pending_embed": "待嵌入:" if lang == "中文" else "Pending:",
            "complete_embed": "嵌入完成" if lang == "中文" else "Embedding Complete",
            "processing_session_files": "处理本次上传的文件:" if lang == "中文" else "Processing files from this session:",
            "auto_detect_chunks": "自动检测需要嵌入的分块" if lang == "中文" else "Auto-detecting chunks that need embedding",
            "processing_all_chunks": "处理所有分块" if lang == "中文" else "Processing all chunks",
            "start_embed": "生成向量" if lang == "中文" else "Generate Embeddings",
            "embed_success": "向量生成完成！" if lang == "中文" else "Embedding complete!",
            "duplicate_ids": "检测到重复ID，已跳过: {ids}" if lang == "中文" else "Duplicate IDs detected, skipped: {ids}",
            "partial_embed": "部分分块因ID重复未被生成向量，其余已完成。" if lang == "中文" else "Some chunks skipped due to duplicate IDs, others done.",
            "embed_fail": "向量生成失败: {err}" if lang == "中文" else "Embedding failed: {err}",

            "manifest_check_title": "#### 📊 Manifest 健康检查" if lang == "中文" else "#### 📊 Manifest Health Check",
            "missing_chunks": "未生成分块的文件: {files}" if lang == "中文" else "Files with no chunks: {files}",
            "all_chunked": "所有文件均已分块。" if lang == "中文" else "All files are chunked.",

            "status_title": "#### 当前分块 & 向量 状态" if lang == "中文" else "#### Current Chunk & Embedding Status",
            "embed_model": "向量模型: **{model}**" if lang == "中文" else "Embedding model: **{model}**",
            "chunk_count": "当前分块总数: **{n}**" if lang == "中文" else "Total Chunks: **{n}**",
            "embed_count": "当前向量数量: **{n}**" if lang == "中文" else "Total Embeddings: **{n}**",
            "progress_label": "向量进度（已入库/分块）" if lang == "中文" else "Embedding Progress (completed/chunks)",

            "manifest_title": "#### 📄 文件处理状态 (manifest)" if lang == "中文" else "#### 📄 File Processing Status (manifest)",
            "manifest_col_file": "文件" if lang == "中文" else "File",
            "manifest_col_nchunks": "分块数" if lang == "中文" else "Chunks",
            "manifest_col_chunkmethod": "分块方式" if lang == "中文" else "Chunk Method",
            "manifest_col_last": "最后处理" if lang == "中文" else "Last Processed",
            "no_manifest": "暂无 manifest.json，尚未预处理。" if lang == "中文" else "No manifest.json, not yet processed.",
        },
        "literature_tab": {
            "header": "文献综述与问答" if lang == "中文" else "Literature Review & QA",
            "step1_title": "### 步骤1：选择项目" if lang == "中文" else "### Step 1: Select Project",
            "step1_info": "请选择要进行文献综述和问答的项目，请确保已在RAG标签中上传并处理PDF。" if lang == "中文" else "Select a project to perform literature review and QA. Please make sure you have already uploaded and processed your PDFs in the RAG tab.",
            "select_project": "文献综述项目选择：" if lang == "中文" else "Select Project for Literature Review:",
            "no_project": "请先选择项目" if lang == "中文" else "Please select a project",
            "no_db_warning": "请先为该项目生成嵌入（见RAG标签）。" if lang == "中文" else "Please generate embeddings for this project first (see RAG tab).",

            "step2_title": "### 步骤2：输入检索问题" if lang == "中文" else "### Step 2: Enter Your Query",
            "step2_info": "描述你的研究问题或信息需求，系统将优化你的检索意图以获得更好结果。" if lang == "中文" else "Describe your research question or information need. The system will help you standardize and optimize your query for better retrieval.",
            "optimize_prompt": "进行检索意图优化（Prompt Optimization）" if lang == "中文" else "Prompt Optimization",
            "query_input": "请输入你的检索问题：" if lang == "中文" else "Enter Your Query:",
            "optimizing": "正在优化检索意图..." if lang == "中文" else "Prompt Optimization in progress...",
            "optimized_prompt": "优化后的检索意图: {prompt}" if lang == "中文" else "Optimized Prompt: {prompt}",

            "step3_title": "### 步骤3：编辑摘要模板" if lang == "中文" else "### Step 3: Customize Summarization Template",
            "step3_info": "你可以自定义摘要输出格式，模板支持分节及学术写作风格。" if lang == "中文" else "You can customize the output format for the summary. The template supports sections and academic writing style.",
            "default_structured": """请用以下结构进行总结：
1. 研究背景
2. 主要发现
3. 挑战
4. 未来方向
5. 结论
6. 关键数据或案例
7. 参考文献""" if lang == "中文" else """Please summarize using the following structure:
1. Research Background
2. Key Findings
3. Challenges
4. Future Directions
5. Conclusions
6. Key Data or Case Studies
7. References""",
            "default_direct": """直接、简明地回答上述问题，仅使用上下文中的信息。如果无法明确回答，则说明"上下文信息不足"。""" if lang == "中文" else """Provide a direct and concise answer to the question above, using only the information from the context. If unable to provide a clear answer, state "Insufficient context information".""",
            "structured_review": "**结构化文献综述**" if lang == "中文" else "**Structured Literature Review**",
            "structured_template": "结构化模板" if lang == "中文" else "Structured Template",
            "direct_answer": "**直接回答**" if lang == "中文" else "**Direct Answer**",
            "direct_template": "直接回答模板" if lang == "中文" else "Direct Answer Template",
            "choose_template": "选择摘要模板风格：" if lang == "中文" else "Choose summary template style:",
            "structured": "结构化" if lang == "中文" else "Structured",
            "direct": "直接回答" if lang == "中文" else "Direct Answer",

            "step4_title": "### 步骤4：检索参数设置与检索" if lang == "中文" else "### Step 4: Retrieval Settings & Run Retrieval",
            "step4_info": "调整检索参数。若无结果，可适当降低相似度阈值。" if lang == "中文" else "Adjust the retrieval parameters. If you get no results, try increasing the maximum distance threshold.",
            "relevance_threshold": "最小相似度阈值：" if lang == "中文" else "Set Minimum Similarity Score (Relevance Threshold):",
            "relevance_help": "值越高匹配越严格，若无结果可适当降低。" if lang == "中文" else "Higher values mean stricter match (more similar). If you get no results, try lowering this value.",
            "num_chunks": "检索块数：" if lang == "中文" else "Select Number of Chunks to Retrieve:",
            "run_retrieval": "执行检索" if lang == "中文" else "Run Retrieval",
            "retrieving": "正在检索相关分块..." if lang == "中文" else "Retrieving relevant chunks...",
            "chunks_found": "{n} 个分块已找到" if lang == "中文" else "{n} Chunks Found",

            "step5_title": "### 步骤5：生成摘要" if lang == "中文" else "### Step 5: Summarize Retrieved Chunks",
            "step5_info": "基于检索内容和你的模板生成结构化摘要。" if lang == "中文" else "Generate a structured summary based on the retrieved content and your template.",
            "select_model": "选择模型：" if lang == "中文" else "Select Model:",
            "model_options": ["gpt-4o", "gpt-4o-mini", "qwen-max", "qwen-plus", "qwen-turbo"],
            "temperature": "Temperature (创造性)：" if lang == "中文" else "Temperature (Creativity):",
            "temp_help": "值越高输出越有创造力，常用范围0.2~1.0" if lang == "中文" else "Higher values produce more creative output. Typical range: 0.2~1.0",
            "max_tokens": "最大输出 tokens：" if lang == "中文" else "Max Tokens:",
            "max_tokens_help": "摘要输出最大token数。" if lang == "中文" else "Maximum number of tokens in the summary output.",
            "log_metrics": "记录token消耗与处理时间" if lang == "中文" else "Log Token Consumption and Processing Time",
            "generate_summary": "生成摘要" if lang == "中文" else "Generate Summary",
            "summarizing": "正在生成摘要..." if lang == "中文" else "Summarizing Retrieved Chunks...",
            "show_time": "处理用时：{time} 秒" if lang == "中文" else "Processing Time: {time} seconds",
            "show_tokens": "总 tokens：{tokens}" if lang == "中文" else "Total Tokens: {tokens}",
            "summary_fail": "摘要生成失败，请检查输入或模板。" if lang == "中文" else "Summary generation failed, please check your input and template.",
            "no_chunks": "无分块可用，请先检索。" if lang == "中文" else "No chunks found for summarization. Please run retrieval first.",
            "basic_prompt": """你获得了以下论文片段：

{context}

这里是你要总结的问题，仅用上下文回答，引用文献请遵循学术风格 [Chicago] 并尽量包含DOI。
#####{query}#####
""" if lang == "中文" else """You are given the following excerpts from research papers:

{context}

And here is the query you want to summarize, use only the information in the context.
Generate reference according formal academic writing style [Chicago style], include DOI whenever available.
#####{query}#####
""",
        },
        "anki_tab": {
            "header": "生成 Anki 卡片" if lang == "中文" else "Generate Anki Cards",
            "no_projects": "未发现项目，请先在文献分析页创建项目。" if lang == "中文" else "No projects found. Please create a project in the Literature Analysis tab first.",
            "select_project": "选择卡片项目：" if lang == "中文" else "Select Project for Cards:",
            "select_project_help": "请选择包含要制作卡片的文档的项目" if lang == "中文" else "Choose the project containing the documents you want to create cards from",
            "please_select_project": "请先选择项目" if lang == "中文" else "Please select a project",
            "preprocess_warning": "请先为该项目预处理并生成嵌入（见RAG标签）。" if lang == "中文" else "Please preprocess and embed documents in this project first (see RAG tab).",
            "using_llm": "使用大语言模型生成高质量卡片" if lang == "中文" else "Using LLM for high-quality card generation",
            "card_type": "卡片类型：" if lang == "中文" else "Card Type:",
            "qa": "问答" if lang == "中文" else "Q&A",
            "cloze": "填空" if lang == "中文" else "Cloze",
            "card_type_help": "问答卡片为问答形式，填空卡片为完型填空" if lang == "中文" else "Q&A creates question-answer pairs, Cloze creates fill-in-the-blank style cards",
            "num_cards": "生成卡片数：" if lang == "中文" else "Number of Cards:",
            "num_cards_help": "要生成多少张卡片" if lang == "中文" else "How many cards to generate",
            "difficulty": "难度：" if lang == "中文" else "Difficulty:",
            "difficulty_options": ["简单", "中等", "困难"] if lang == "中文" else ["Easy", "Medium", "Hard"],
            "difficulty_default": "中等" if lang == "中文" else "Medium",
            "difficulty_help": "控制问题的复杂程度" if lang == "中文" else "Controls the complexity of the questions",
            "detail_level": "详细程度：" if lang == "中文" else "Detail Level:",
            "detail_level_options": ["简洁", "中等", "详细"] if lang == "中文" else ["Concise", "Medium", "Detailed"],
            "detail_level_default": "中等" if lang == "中文" else "Medium",
            "detail_level_help": "控制每张卡片的信息量" if lang == "中文" else "Controls how much information to include in each card",
            "query_input": "请输入主题或知识点：" if lang == "中文" else "Enter your query:",
            "query_help": "输入你想制作卡片的主题或概念，系统会自动检索相关内容" if lang == "中文" else "Enter the topic or concept you want to create cards for. The system will find relevant content from your documents.",
            "optimize_prompt": "优化查询" if lang == "中文" else "Optimize Query",
            "optimize_help": "使用AI优化您的查询以获得更好的检索效果" if lang == "中文" else "Use AI to optimize your query for better retrieval",
            "optimizing": "正在优化查询..." if lang == "中文" else "Optimizing query...",
            "optimized_query": "优化后的查询" if lang == "中文" else "Optimized Query",
            "current_query": "当前查询" if lang == "中文" else "Current Query",
            "standardized_query": "使用查询" if lang == "中文" else "Using query",
            "retrieval_complete": "检索完成！" if lang == "中文" else "Retrieval completed!",
            "question": "问题" if lang == "中文" else "Question",
            "answer": "答案" if lang == "中文" else "Answer", 
            "extra_info": "补充信息" if lang == "中文" else "Extra Info",
            "top_k": "检索Top-K分块：" if lang == "中文" else "Top-K Chunks to Retrieve:",
            "top_k_help": "每次检索多少分块用于卡片生成" if lang == "中文" else "How many relevant chunks to retrieve for card generation",
            "relevance_threshold": "最小相似度分数：" if lang == "中文" else "Minimum Similarity Score (Relevance Threshold):",
            "relevance_threshold_help": "值越高匹配越严格，若无结果可适当降低" if lang == "中文" else "Higher values mean stricter match (more similar). If you get no results, try lowering this value.",
            "retrieve_chunks": "检索相关分块" if lang == "中文" else "Retrieve Relevant Chunks",
            "retrieving": "正在检索相关分块..." if lang == "中文" else "Retrieving relevant chunks...",
            "preview_chunks": "检索到的分块预览：" if lang == "中文" else "Preview of retrieved chunks:",
            "please_enter_query": "请先输入检索主题" if lang == "中文" else "Please enter a query first",
            "chunks_retrieved": "检索到 {n} 个相关分块。" if lang == "中文" else "Retrieved {n} relevant chunks.",
            "chunk_id": "**分块 {idx}:** {src}" if lang == "中文" else "**Chunk {idx}:** {src}",
            "no_chunks_found": "未检索到相关分块，请尝试降低阈值或增大Top-K。" if lang == "中文" else "No relevant chunks found. Try lowering the threshold or increasing Top-K.",
            "generate_cards": "生成卡片" if lang == "中文" else "Generate Cards",
            "please_retrieve_chunks": "请先检索相关分块" if lang == "中文" else "Please retrieve relevant chunks first",
            "generating_cards": "正在生成卡片..." if lang == "中文" else "Generating cards...",
            "llm_output": "LLM输出（CSV格式）：" if lang == "中文" else "LLM Output (CSV format):",
            "no_content_preview": "无内容可预览。" if lang == "中文" else "No content to preview.",
            "error_generating": "生成卡片出错: {err}" if lang == "中文" else "Error generating cards: {err}",
            "export_csv": "导出为CSV" if lang == "中文" else "Export to CSV",
            "csv_saved": "CSV文件已保存至: {path}" if lang == "中文" else "CSV file saved to: {path}",
            "download_cards": "下载卡片" if lang == "中文" else "Download Cards",
            "cards_generated_success": "✅ 成功生成 {count} 张卡片" if lang == "中文" else "✅ Successfully generated {count} cards",
            "invalid_card_data": "无法解析任何有效的卡片数据" if lang == "中文" else "Unable to parse any valid card data",
            "invalid_row_format": "第 {row_num} 行格式不正确: {row}" if lang == "中文" else "Row {row_num} format incorrect: {row}",
            "no_valid_csv": "LLM没有返回有效的CSV格式数据" if lang == "中文" else "LLM did not return valid CSV format data"
        },
        "litmap_tab": {
            "header": "LitMap 知识图谱" if lang == "中文" else "LitMap Knowledge Graph",
            "description": "从研究文献构建和可视化知识图谱。处理、审查和合并实体/关系数据，完全可控。" if lang == "中文" else "Build and visualize a knowledge graph from your research literature. Process, review, and merge entity/relation data with full control.",
            "step1_title": "步骤1：选择项目" if lang == "中文" else "Step 1: Select Project",
            "step1_info": "选择一个项目来构建和审查知识图谱。确保您已在RAG标签页中处理了PDF文件。" if lang == "中文" else "Select a project to build and review the knowledge graph. Make sure you have processed your PDFs in the RAG tab.",
            "no_projects": "未找到项目。请先在RAG标签页中创建项目。" if lang == "中文" else "No projects found. Please create a project in the RAG tab first.",
            "select_project": "选择项目：" if lang == "中文" else "Select Project:",
            "no_project": "请选择一个项目。" if lang == "中文" else "Please select a project.",
            "no_chunks_warning": "未找到已处理的文本块。请先在RAG标签页中预处理文件。" if lang == "中文" else "No processed chunks found. Please preprocess files in the RAG tab first.",
            "step2_title": "步骤2：配置提取设置" if lang == "中文" else "Step 2: Configure Extraction Settings",
            "step2_info": "设置实体/关系类型、去重和其他提取参数。" if lang == "中文" else "Set up entity/relation types, deduplication, and other extraction parameters.",
            "progress_label": "Progress",
            "last_processed_at": "Last processed at",
            "max_chunks": "Maximum Chunks to Process",
            "max_chunks_help": "How many chunks to process at once.",
            "confidence_threshold": "Confidence Threshold",
            "confidence_help": "Minimum confidence for entities/relations.",
            "enable_deduplication": "Enable Entity Deduplication",
            "deduplication_help": "Remove duplicate entities.",
            "physics_enabled": "Enable Physics Simulation",
            "physics_help": "Use physics for network visualization.",
            "advanced_optimization": "🔧 高级实体优化" if lang == "中文" else "🔧 Advanced Entity Optimization",
            "optimization_description": "实体优化使用两个阶段：阶段1（语言学规范化）始终启用，阶段2（语义相似性）是可选的且计算密集。" if lang == "中文" else "Entity optimization uses two phases: Phase 1 (linguistic normalization) is always enabled, while Phase 2 (semantic similarity) is optional and computationally intensive.",
            "enable_semantic": "启用语义相似性（阶段2）" if lang == "中文" else "Enable Semantic Similarity (Phase 2)",
            "semantic_help": "使用AI模型检测语义相似的实体（例如，'ML'和'machine learning'）。需要sentence-transformers包并增加处理时间。" if lang == "中文" else "Use AI models to detect semantically similar entities (e.g., 'ML' and 'machine learning'). Requires sentence-transformers package and increases processing time.",
            "improved_extraction": "启用改进提取（预规范化）" if lang == "中文" else "Enable Improved Extraction (Pre-normalization)",
            "improved_extraction_help": "在提取过程中规范化实体而不是后处理。这减少了源头的不一致性并提高了效率。" if lang == "中文" else "Normalize entities during extraction instead of post-processing. This reduces inconsistencies at the source and improves efficiency.",
            "similarity_threshold": "语义相似性阈值" if lang == "中文" else "Semantic Similarity Threshold",
            "threshold_help": "更高的值 = 更保守的合并。推荐：0.80-0.90" if lang == "中文" else "Higher values = more conservative merging. Recommended: 0.80-0.90",
            "semantic_warning": "⚠️ 语义相似性将显著增加处理时间。考虑先用少量分块测试。" if lang == "中文" else "⚠️ Semantic similarity will increase processing time significantly. Consider testing with a small number of chunks first.",
            "improved_extraction_info": "✨ 改进提取在实体提取过程中应用规范化，从一开始就产生更一致的实体。" if lang == "中文" else "✨ Improved extraction applies normalization during entity extraction, resulting in more consistent entities from the start.",
            "phase1_features": "阶段1（始终启用）" if lang == "中文" else "Phase 1 (Always Enabled)",
            "phase1_description": "• 规范化单复数形式（例如，'systematic reviews' → 'systematic review'）\n• 展开缩写（例如，'ML' → 'machine learning'）\n• 标准化标点符号和词序\n• 删除完全匹配的重复实体" if lang == "中文" else "• Normalizes singular/plural forms (e.g., 'systematic reviews' → 'systematic review')\n• Expands abbreviations (e.g., 'ML' → 'machine learning')\n• Standardizes punctuation and word order\n• Removes duplicate entities with exact name matches",
            "phase1_extraction_note": "\n• **在提取过程中应用**以实现最大效率" if lang == "中文" else "\n• **Applied during extraction** for maximum efficiency",
            "phase1_postprocess_note": "\n• **在提取后应用**作为后处理" if lang == "中文" else "\n• **Applied after extraction** as post-processing",
            "phase2_features": "阶段2（语义相似性）" if lang == "中文" else "Phase 2 (Semantic Similarity)",
            "phase2_description": "• 使用AI嵌入检测语义相似的实体\n• 合并意思相似但表达不同的实体\n• 维护实体来源和置信度信息" if lang == "中文" else "• Detects semantically similar entities using AI embeddings\n• Merges entities with similar meanings but different expressions\n• Maintains entity source and confidence information",
            "entity_types": "Select Entity Types",
            "entity_types_help": "Choose which entity types to extract.",
            "enable_entity_custom": "Enable custom entity types",
            "custom_entity_types": "Custom entity types (comma separated)",
            "custom_entity_types_help": "Enter custom entity types, comma separated.",
            "relation_types": "Select Relation Types",
            "relation_types_help": "Choose which relation types to extract.",
            "enable_relation_custom": "Enable custom relation types",
            "custom_relation_types": "Custom relation types (comma separated)",
            "custom_relation_types_help": "Enter custom relation types, comma separated.",
            "reprocess_all": "全部重新处理" if lang == "中文" else "Reprocess All",
            "reprocess_all_help": "重置所有分块状态并从头重新处理所有数据" if lang == "中文" else "Reset all chunk status and reprocess all data from scratch.",
            "reprocess_all_warning": "将处理所有分块（忽略上面的限制）并删除现有数据。" if lang == "中文" else "Will process ALL chunks (ignores the limit above) and delete existing data.",
            "reprocess_warning": "这将删除所有现有数据并从头重新处理所有内容。确定继续？" if lang == "中文" else "This will delete all existing data and reprocess everything from scratch. Continue?",
            "yes_reprocess": "是的，全部重新处理" if lang == "中文" else "Yes, Reprocess All",
            "cancel": "取消" if lang == "中文" else "Cancel",
            "reprocess_select": "选择性重新处理" if lang == "中文" else "Reprocess Select Chunks",
            "reprocess_select_help": "清空数据库并从头处理选定数量的分块（适合小规模测试）" if lang == "中文" else "Clear database and process selected chunks from scratch (ideal for small-scale testing).",
            "reprocess_select_info": "将清空数据库并从头处理 {n} 个分块。" if lang == "中文" else "Will clear database and process {n} chunks from scratch.",
            "initializing_select_reprocess": "正在初始化选择性重新处理（从头开始）..." if lang == "中文" else "Initializing selective reprocessing (from scratch)...",
            "selective_reprocessing": "🔄 选择性重新处理：正在从头处理 {n} 个选定的分块..." if lang == "中文" else "🔄 Selective reprocessing: Processing {n} selected chunks from scratch...",
            "selective_complete": "选择性重新处理完成！从 {c} 个分块中处理了 {n} 个实体和 {r} 个关系。" if lang == "中文" else "Selective reprocessing complete! Processed {n} entities and {r} relations from {c} chunks.",
            "no_chunks_to_reprocess": "没有可用于选择性重新处理的分块。" if lang == "中文" else "No chunks available for selective reprocessing.",
            "initializing_full_reprocess": "开始从头完全重新处理..." if lang == "中文" else "Starting full reprocessing from scratch...",
            "full_reprocessing": "🔄 完全重新处理：正在处理所有 {n} 个分块..." if lang == "中文" else "🔄 Full reprocessing: Processing all {n} chunks...",
            "full_reprocess_complete": "完全重新处理完成！处理了 {n} 个实体和 {r} 个关系。" if lang == "中文" else "Full reprocessing complete! Processed {n} entities and {r} relations.",
            "incremental_complete": "增量处理完成！发现 {n} 个新实体和 {r} 个新关系。请审查并合并。" if lang == "中文" else "Incremental processing complete! Found {n} new entities and {r} new relations. Please review and merge.",
            "continue_from_last": "从上次继续" if lang == "中文" else "Continue from Last",
            "continue_from_last_help": "只处理未处理的分块，保留历史记录" if lang == "中文" else "Only process unprocessed chunks, keep history.",
            "continue_from_last_info": "遵循上面的分块限制并保留现有数据。" if lang == "中文" else "Respects the chunk limit above and preserves existing data.",
            "dry_run": "试运行（仅预览）" if lang == "中文" else "Dry Run (Preview Only)",
            "clear_status": "清空状态" if lang == "中文" else "Clear Status",
            "clear_status_help": "清空进度和统计显示" if lang == "中文" else "Clear progress and stats display.",
            "initializing_extraction": "正在初始化抽取..." if lang == "中文" else "Initializing extraction...",
            "no_unprocessed_chunks": "没有未处理的分块需要处理" if lang == "中文" else "No unprocessed chunks to process.",
            "processing_chunks": "📝 增量处理：正在处理 {n} 个分块..." if lang == "中文" else "📝 Incremental processing: Processing {n} chunks...",
            "estimated_processing": "Estimated processing: {n} chunks, estimated time {t} minutes, estimated cost ${c}",
            "processing_progress": "Progress: {current}/{total} ({percent:.1%})",
            "extraction_error": "Extraction error",
            "extraction_complete": "Extraction complete: {entities} entities, {relations} relations.",
            "step3_title": "Step 3: Data Review & Merge",
            "step3_info": "Preview newly extracted data, load all historical data, and decide when to merge new data into the main database.",
            "preview_new_data": "Preview New Data",
            "load_history_data": "Load All History",
            "merge_new_data": "Merge New Data to Main DB",
            "showing_new_data": "Currently showing: newly processed data (not yet merged)",
            "showing_history_data": "Currently showing: historical data (already merged/saved)",
            "history_loaded": "All historical data loaded.",
            "step4_title": "Step 4: Statistics",
            "total_entities": "Total Entities",
            "total_relations": "Total Relations",
            "avg_entity_confidence": "Avg. Entity Confidence",
            "avg_relation_confidence": "Avg. Relation Confidence",
            "most_connected": "最关联实体" if lang == "中文" else "Most Connected Entities",
            "no_connected_entities": "未找到关联实体。" if lang == "中文" else "No connected entities found.",
            "entity_name": "实体名称" if lang == "中文" else "Entity Name",
            "entity_type": "类型" if lang == "中文" else "Type", 
            "total_connections": "总连接数" if lang == "中文" else "Total Connections",
            "as_source": "作为源" if lang == "中文" else "As Source",
            "as_target": "作为目标" if lang == "中文" else "As Target",
            "unique_partners": "独特伙伴数" if lang == "中文" else "Unique Partners",
            "relation_diversity": "关系类型数" if lang == "中文" else "Relation Types",
            "avg_confidence": "平均置信度" if lang == "中文" else "Avg Confidence",
            "influence_score": "影响力评分" if lang == "中文" else "Influence Score",
            "most_connected_explanation": "📊 理解最关联实体" if lang == "中文" else "📊 Understanding Most Connected Entities",
            "detailed_table": "📊 详细分析" if lang == "中文" else "📊 Detailed Analysis",
            "summary_cards": "📋 概览卡片" if lang == "中文" else "📋 Summary Cards",
            "relation_types": "关系类型" if lang == "中文" else "Relationship Types",
            "connected_entities_help": """
**影响力评分**：总连接数与平均置信度的组合权重
- **总连接数**：此实体参与了多少个关系
- **作为源/目标**：关系的方向性（主动vs被动角色）
- **独特伙伴数**：连接到的不同实体数量
- **关系类型数**：不同关系类型的数量
- **平均置信度**：AI提取实体的平均置信度

影响力评分高的实体通常是您文献中的核心概念、关键方法或重要研究主题。

**颜色编码：**
- 🔥 **高影响力** (评分 ≥ 10)：核心研究概念
- ⭐ **中等影响力** (评分 5-10)：重要支撑概念  
- 📍 **新兴概念** (评分 < 5)：特定或细分概念
            """ if lang == "中文" else """
**Influence Score**: Combination of total connections weighted by average confidence
- **Total Connections**: How many relationships this entity participates in
- **As Source/Target**: Direction of relationships (active vs passive role)
- **Unique Partners**: Number of different entities connected to
- **Relation Diversity**: Number of different relationship types
- **Avg Confidence**: Average AI confidence in entity extraction

Entities with high influence scores are typically central concepts, key methodologies, or important research topics in your literature.

**Color Coding:**
- 🔥 **High Impact** (Score ≥ 10): Core research concepts
- ⭐ **Moderate Impact** (Score 5-10): Important supporting concepts  
- 📍 **Emerging** (Score < 5): Specific or niche concepts
            """,
            "step5_title": "Step 5: Visualization",
            "building_graph": "Building knowledge graph...",
            "graph_nodes": "Graph Nodes",
            "graph_edges": "Graph Edges",
            "graph_density": "Graph Density",
            "visualization_type": "Visualization Type:",
            "interactive_network": "Interactive Network",
            "statistics_dashboard": "Statistics Dashboard",
            "creating_visualization": "Creating interactive network...",
            "creating_dashboard": "Creating statistics dashboard...",
            "export_options": "Export Options",
            "export_graph_data": "Export Graph Data (GEXF)",
            "graph_exported": "Graph data exported to {path}",
            "export_visualization": "Export Visualization (HTML)",
            "visualization_exported": "Visualization exported to {path}",
            "insufficient_data": "Not enough data to visualize. Please process or load more data.",
            "select_project_and_configure": "Please select a project and configure extraction settings."
        }
    }
